import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import theme from '../theme'
import "./globals.css";
import {UserProvider} from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
      <html lang="en">
          <UserProvider>
              <body className={inter.className}>
                  <AppRouterCacheProvider options={{enableCssLayer: true}}>
                      {children}
                  </AppRouterCacheProvider>
              </body>
          </UserProvider>
      </html>
  );
}
